Image:
  using_mlp: True
  mode: "grid"

MLP:
  in_features: 8
  out_features: 3
  nonlinearity: "relu"
  num_hidden_layers: 2
  hidden_features: 256
  outermost_linear: True
  # weight_init: None


Encoding:
  dim_feat: 8
  gridSize: [100,100]

Solver:
 lr: 1.e-4