Image:
  using_mlp: True
  mode: "phasor_sample"

MLP:
  in_features: 8
  out_features: 3
  nonlinearity: "relu"
  num_hidden_layers: 3
  hidden_features: 256
  outermost_linear: True
  # weight_init: None

Encoding:
  dim_feat: 8
  gaussion_var: 0 #1.e-3
  # freqSize: [100,100]
  freqSize: [8,8]
  freq_log: [False,True]
  TV_weight: 0 #1.e+5

Solver:
 lr: 1.e-4