Image:
  using_mlp: True
  mode: "pe"

MLP:
  in_features: 2
  out_features: 3
  nonlinearity: "sine"
  num_hidden_layers: 3
  hidden_features: 256
  outermost_linear: True
  # weight_init: None


Encoding:
  in_features: 2
  sidelength: 1
  use_nyquist: False
  num_frequencies: 0


Solver:
 lr: 1.e-4